### ISSUE TITLE
Additional docs for existing campus user in Getting Started guide

### ISSUE THREAD

**Issue by tenken** [ucsb/github-guide#12]
I attempted to join the ucsb org on github and as a campus member with a pre-existing github account the current set of directions led me astray to link my existing (personal) account to Github as a member of the ucsb org.

I will supply a PR with proposed updated `Getting Started` directions.

**Comment by secabeen** [comment]
That's what happened to me, although I don't mind it too much either.  It's pretty clear when I'm working with a org repo versus one of my persons ones, but I can see how other people might want to make a different choice.

**Comment by kevinwucodes** [comment]
closing issue due to https://github.com/ucsb/github-guide/pull/13
