### ISSUE TITLE
I screwed up the process for our functional account

### ISSUE THREAD

**Issue by collaborate-gauchospace-dev** [ucsb/github-guide#14]
I tried to create an account for our functional account, collaborate-gauchospace.dev@ucsb.edu. The username would not accept a period character, so I created a username collaborate-gauchospace-dev using that email address.

But I cannot log in with SSO to become a member.

When I log in to github, I'm directed to the /ucsb page.

Can you help me get this sorted out? I am dsoini@ucsb.edu.

**Comment by jwoods-ucsb** [comment]
Sounds like an identity issue. Taking this offline for now. See direct email
