### ISSUE TITLE
Sharing a repo with read-only access

### ISSUE THREAD

**Issue by veronica-r** [ucsb/github-guide#16]
I just created a team for my research group and would like to share a repo with my team, but with read-only access. I fear I made a mistake, however, and just transferred the repo (which was a private repo in my personal account) to the 'ucsb' organization - now I don't seem to have access to adjust the repo settings at all. How can I regain control of this and adjust the access settings?

**Comment by kevinwucodes** [comment]
@veronica-r I can confirm that you transferred the repo so I've granted you admin access back.
