### ISSUE TITLE
GitHub Education Upgrade to a class org

### ISSUE THREAD

**Issue by syoh** [ucsb/github-guide#19]
I created (and am an owner of) an [org for a class I am a part of teaching](https://github.com/ucsb-ds-capstone-2021), and I am trying to upgrade it to GitHub Team org.

However, when I try to upgrade it with [GitHub education](https://education.github.com/toolbox/offers/github-org-upgrades), I encounter an error that I am not an admin of the organization.

I am fairly certain that the org I created belongs to UCSB, and that is the only reason I can think of that would give me an error such as this:
![image](https://user-images.githubusercontent.com/1441512/103851248-2e5e1e00-505e-11eb-9261-1164f99057f4.png)

Could someone look into this for me or help me to figure out why I am seeing this? GitHub support has not been responsive to my support request.

Thank you for any help/insight about this

**Comment by jwoods-ucsb** [comment]
Hello @syoh UCSB has already signed up for Github for Education. This is the primary Organization is [github.com/ucsb](https://github.com/ucsb). You can create repositories within the UCSB org, but not additional organizations. I suggest moving the repos into the primary organization and then creating teams to control access.

**Comment by syoh** [comment]
Thank you, Jim. I received help from GitHub and this is resolved.
