### ISSUE TITLE
Org setting change - forking private repos

### ISSUE THREAD

**Issue by jwoods-ucsb** [ucsb/github-guide#3]
Allow forking of private repos. This is globally disabled at the moment, but we have a use case that has a private repo that needs to allow forking. This would become a per repo option.

Include new documentation in the github-guide

**Comment by smaglio81** [comment]
Hey @jwoods-ucsb, what’s the use case behind not allowing private repos to be forked?

**Comment by jwoods-ucsb** [comment]
@smaglio81 It's private for a reason. If the repo is forked and the forked repo is public, that kind of kills the private aspect. It's better to let repo admins decide anyway. We have changed the UCSB org setting, so I am closing this issue.

thanks
