### ISSUE TITLE
Repository Imports to the UCSB Organization hang indefinitely

### ISSUE THREAD

**Issue by zanpreston** [ucsb/github-guide#6]
When importing a repository and selecting the UCSB Org to be the owner of the repository, the process states that it starts, but then just hangs indefinitely (days is as far as I've gone). Each step of the process is near instantaneous when selecting a personal account as the owner.

**Comment by jwoods-ucsb** [comment]
@zanpreston I am wondering if it's a permission issue to the organization. can we give this a try? 

Set up a test repo on github.ucsb.edu and give me access to it. I will then try to [import](https://help.github.com/en/github/importing-your-projects-to-github/importing-a-repository-with-github-importer) it directly to the UCSB Github Org.

Let's try both a public and private repo.

Thanks

**Comment by zanpreston** [comment]
@jwoods-ucsb Here's a link to a public test repo. 
https://github.ucsb.edu/zan/test-with-features

How do you want to do a private repo?

**Comment by jwoods-ucsb** [comment]
@zanpreston I am asked to log into github.ucsb.edu to see the public repo. Want to create an account for me?

**Comment by zanpreston** [comment]
@jwoods-ucsb I gave @kevinwucodes some credentials to an account a while back. If he doesn't still have access to them, I can get you them via the Firefox Send or through Signal if you have it.

**Comment by jwoods-ucsb** [comment]
@kevinwucodes. Can you attempt an import from the github.ucsb.edu to github.com organization for the above test repo?

**Comment by kevinwucodes** [comment]
I wrote this to @zanpreston in an email but I probably should have documented this here.  @zanpreston I would like to try a test migration to see if I can reproduce the error in your test migration from github.ucsb.edu to github.com but I dont think I can because github.ucsb.edu is showing a license expiration.

I have the credentials you sent to me from before.

I will submit a help ticket into GitHub Enterprise support but would need to be able to connect to github.ucsb.edu at some point.

**Comment by kevinwucodes** [comment]
I emailed GitHub Enterprise support and this is their reply:

> In order to import a repository with [GitHub Importer](https://help.github.com/en/github/importing-your-projects-to-github/importing-a-repository-with-github-importer), the source server will need to be accessible from the internet.
>
> Another alternative is to import a [Git repository using the command line](https://help.github.com/en/github/importing-your-projects-to-github/importing-a-git-repository-using-the-command-line), which would bypass the need for connectivity between GitHub.com and your on-premise GitHub Enterprise Server appliance.
>
> If you're sure your appliance is reachable from the internet and are unable to import via the command line, can you please let us know which user on GitHub.com is attempting the import, and which target repository they are trying to import to?

Both of these links fall under the [Importing your projects to Github](https://help.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github) parent menu link.

@zanpreston can you give one of these a try and lets see what happens next?

**Comment by zanpreston** [comment]
@kevinwucodes 

I do know that bring a repository over to Github.com works when using the command line. Given how git works, it's not really importing, but rather making a local mirror, then pushing to another mirror that you've manually created on Github.com.

I will confirm with Mike Edwards one more time this morning, but I'm guessing I will just close this issue, given we're now considering our GitHub Enterprise EOL.

I will update later today after checking with Mike.

**Comment by zanpreston** [comment]
@jwoods-ucsb @kevinwucodes I have confirmed that we'll close this issue, now that the service is End Of Life. The idea is that, at the very least, users were given at least 6-weeks notice and should at least have locally cloned copies of their repositories which could then be pushed to Github.com.
