### ISSUE TITLE
Request for write access on repositories

### ISSUE THREAD

**Issue by stevenlandis** [ucsb/github-guide#8]
Hi,
I'm migrating two repositories from github.ucsb.edu. I was unable to migrate the repositories directly to github.com so I migrated them to my personal github and then transferred ownership to ucsb. The repositories are now on ucsb's github, but I only have read access. Is there some way I can get write access for these repositories?

**Comment by jwoods-ucsb** [comment]
I have updated [ADDICT](https://github.com/ucsb/ADDICT) and [ADDICT3](https://github.com/ucsb/ADDICT3) so that you are Admin on both. Let me know if you have any other issues. Thanks
